import type { Problem } from "../types.js";
import { objectId } from "../values.js";
import {
  CUSTOMERS,
  EMPLOYEES,
  INVOICES,
  ORDERS,
  PRODUCTS,
  REVIEWS,
  SESSIONS,
  TICKETS,
} from "./datasets.js";

export const easyProblems: Problem[] = [
  {
    id: "easy-category-equality",
    title: "Books in the catalogue",
    difficulty: "easy",
    operation: "find",
    statement:
      "The merchandising team wants to review every product that belongs to the books category. Write the MongoDB query that returns those documents.",
    clues: ["every product that belongs to the books category"],
    sql: "SELECT * FROM products WHERE category = 'books';",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "Start with `db.products.find(...)`.",
      "An equality filter is a document of `{ field: value }`.",
      "Filter on `category` with the string \"books\".",
    ],
    referenceAnswer: 'db.products.find({ category: "books" })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { category: "books" } },
      },
    ],
  },
  {
    id: "easy-price-less-than",
    title: "Bargain bin",
    difficulty: "easy",
    operation: "find",
    statement:
      "The storefront wants to feature every product priced under 20. Return all matching products.",
    clues: ["every product priced under 20"],
    sql: "SELECT * FROM products WHERE price < 20;",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "Comparison operators live inside the field value.",
      "The \"less than\" operator is `$lt`.",
      "Write `{ price: { $lt: 20 } }`.",
    ],
    referenceAnswer: "db.products.find({ price: { $lt: 20 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { price: { $lt: 20 } } },
      },
    ],
  },
  {
    id: "easy-order-status",
    title: "Shipped orders",
    difficulty: "easy",
    operation: "find",
    statement:
      "Support wants a list of every order that has already shipped so they can confirm delivery windows.",
    clues: ["every order that has already shipped"],
    sql: "SELECT * FROM orders WHERE status = 'shipped';",
    collection: "orders",
    sampleDocuments: ORDERS,
    hints: [
      "The documents live in the `orders` collection.",
      "Filter with an equality match.",
      "Match `status` against the string \"shipped\".",
    ],
    referenceAnswer: 'db.orders.find({ status: "shipped" })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "orders" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { status: "shipped" } },
      },
    ],
  },
  {
    id: "easy-findone-by-id",
    title: "Open a customer profile",
    difficulty: "easy",
    operation: "find",
    statement:
      "A support agent opens a single customer profile from the CRM. Fetch the one customer whose _id is ObjectId(\"66f1a2b3c4d5e6f7a8b9c0d1\").",
    clues: ["the one customer whose _id is ObjectId(\"66f1a2b3c4d5e6f7a8b9c0d1\")"],
    sql: "SELECT * FROM customers WHERE _id = '66f1a2b3c4d5e6f7a8b9c0d1';",
    collection: "customers",
    sampleDocuments: CUSTOMERS,
    hints: [
      "When you expect at most one document, `findOne` is the natural method.",
      "Wrap the id literal in `ObjectId(...)`.",
      "There is exactly one match, so `find` is also accepted here.",
    ],
    referenceAnswer: 'db.customers.findOne({ _id: ObjectId("66f1a2b3c4d5e6f7a8b9c0d1") })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "customers" } },
      {
        id: "method",
        label: "Method",
        expectation: { kind: "method", method: "findOne", equivalents: ["find"] },
      },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { _id: objectId("66f1a2b3c4d5e6f7a8b9c0d1") } },
      },
    ],
  },
  {
    id: "easy-projection",
    title: "Names and emails only",
    difficulty: "easy",
    operation: "find",
    statement:
      "The marketing export only needs two fields per customer. Return just the name and email of every customer.",
    clues: ["just the name and email of every customer"],
    sql: "SELECT name, email FROM customers;",
    collection: "customers",
    sampleDocuments: CUSTOMERS,
    hints: [
      "Projection is the second argument to `find`.",
      "Include a field by setting it to `1`.",
      "An empty filter `{}` returns every document.",
    ],
    referenceAnswer: "db.customers.find({}, { name: 1, email: 1 })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "customers" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { name: 1, email: 1 },
          variants: [{ name: 1, email: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-deactivate-customer",
    title: "Deactivate a customer",
    difficulty: "easy",
    operation: "update",
    statement:
      "A customer asked to be removed from all campaigns. Set the active flag of the account with email \"carol@example.com\" to false.",
    clues: ["Set the active flag of the account with email \"carol@example.com\" to false"],
    sql: "UPDATE customers SET active = false WHERE email = 'carol@example.com';",
    collection: "customers",
    sampleDocuments: CUSTOMERS,
    hints: [
      "Use `db.customers.updateOne(filter, update)`.",
      "The `$set` operator assigns field values.",
      "`{ $set: { active: false } }`.",
    ],
    referenceAnswer:
      'db.customers.updateOne({ email: "carol@example.com" }, { $set: { active: false } })',
    rubric: [
      {
        id: "collection",
        label: "Collection",
        weight: 10,
        expectation: { kind: "collection", name: "customers" },
      },
      { id: "method", label: "Method", weight: 20, expectation: { kind: "method", method: "updateOne" } },
      {
        id: "filter",
        label: "Filter condition",
        weight: 30,
        expectation: { kind: "filter", doc: { email: "carol@example.com" } },
      },
      {
        id: "update",
        label: "Update document",
        weight: 40,
        expectation: { kind: "update", doc: { $set: { active: false } } },
      },
    ],
  },
  {
    id: "easy-in-stock",
    title: "Everything in stock",
    difficulty: "easy",
    operation: "find",
    statement:
      "The warehouse dashboard needs every product that currently has stock on hand, meaning a stock value greater than zero.",
    clues: ["every product that currently has stock on hand", "a stock value greater than zero"],
    sql: "SELECT * FROM products WHERE stock > 0;",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "Use a comparison operator on `stock`.",
      "The \"greater than\" operator is `$gt`.",
      "Zero is the threshold, and the comparison is strict.",
    ],
    referenceAnswer: "db.products.find({ stock: { $gt: 0 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { stock: { $gt: 0 } } },
      },
    ],
  },
  {
    id: "easy-well-rated",
    title: "Highly rated products",
    difficulty: "easy",
    operation: "find",
    statement:
      "A recommendation widget only shows products rated 4.5 or higher. Return those products.",
    clues: ["products rated 4.5 or higher"],
    sql: "SELECT * FROM products WHERE rating >= 4.5;",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "\"At least\" means greater than or equal to.",
      "Use `$gte`.",
      "`{ rating: { $gte: 4.5 } }`.",
    ],
    referenceAnswer: "db.products.find({ rating: { $gte: 4.5 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { rating: { $gte: 4.5 } } },
      },
    ],
  },
  {
    id: "easy-clear-clearance-stock",
    title: "Zero out clearance stock",
    difficulty: "easy",
    operation: "update",
    statement:
      "The clearance range has been pulled from sale, so reset the stock of every product in the clearance category to 0.",
    clues: ["reset the stock of every product in the clearance category to 0"],
    sql: "UPDATE products SET stock = 0 WHERE category = 'clearance';",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "Several documents change at once, so use `updateMany`.",
      'Filter on `{ category: "clearance" }`.',
      "Use `$set` to assign the new stock value.",
    ],
    referenceAnswer: 'db.products.updateMany({ category: "clearance" }, { $set: { stock: 0 } })',
    rubric: [
      {
        id: "collection",
        label: "Collection",
        weight: 10,
        expectation: { kind: "collection", name: "products" },
      },
      {
        id: "method",
        label: "Method",
        weight: 20,
        expectation: { kind: "method", method: "updateMany" },
      },
      {
        id: "filter",
        label: "Filter condition",
        weight: 30,
        expectation: { kind: "filter", doc: { category: "clearance" } },
      },
      {
        id: "update",
        label: "Update document",
        weight: 40,
        expectation: { kind: "update", doc: { $set: { stock: 0 } } },
      },
    ],
  },
  {
    id: "easy-books-pricelist",
    title: "Books price list",
    difficulty: "easy",
    operation: "find",
    statement:
      "Build a price list for the books category that shows only each product's name and price.",
    clues: ["a price list for the books category", "shows only each product's name and price"],
    sql: "SELECT name, price FROM products WHERE category = 'books';",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "This combines a filter with a projection.",
      "The filter goes first, the projection second.",
      "`{ category: \"books\" }` then `{ name: 1, price: 1 }`.",
    ],
    referenceAnswer: 'db.products.find({ category: "books" }, { name: 1, price: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { category: "books" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: { kind: "projection", doc: { name: 1, price: 1 } },
      },
    ],
  },
  {
    id: "easy-gold-tier-list",
    title: "Gold tier shortlist",
    difficulty: "easy",
    operation: "find",
    statement:
      "Growth wants a list of every customer on the gold tier, showing only each customer's name and tier.",
    clues: ["every customer on the gold tier", "showing only each customer's name and tier"],
    sql: "SELECT name, tier FROM customers WHERE tier = 'gold';",
    collection: "customers",
    sampleDocuments: CUSTOMERS,
    hints: [
      "An equality match is a plain `{ field: value }` document.",
      "The projection is the second argument and includes fields with `1`.",
      'Filter on `{ tier: "gold" }`, then project `{ name: 1, tier: 1 }`.',
    ],
    referenceAnswer: 'db.customers.find({ tier: "gold" }, { name: 1, tier: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "customers" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { tier: "gold" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { name: 1, tier: 1 },
          variants: [{ name: 1, tier: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-customers-over-40",
    title: "Account ownership review",
    difficulty: "easy",
    operation: "find",
    statement:
      "The compliance team needs a list of every customer older than 40 so they can review account ownership.",
    clues: ["every customer older than 40"],
    sql: "SELECT * FROM customers WHERE age > 40;",
    collection: "customers",
    sampleDocuments: CUSTOMERS,
    hints: [
      "Reach for a comparison operator on `age`.",
      "\"Older than\" is a strict comparison, so `$gt`.",
      "`{ age: { $gt: 40 } }`.",
    ],
    referenceAnswer: "db.customers.find({ age: { $gt: 40 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "customers" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { age: { $gt: 40 } } },
      },
    ],
  },
  {
    id: "easy-upgrade-customer-tier",
    title: "Move a customer up a tier",
    difficulty: "easy",
    operation: "update",
    statement:
      "The retention team has upgraded Dana Scully. Set the tier of the account with email \"dana@example.com\" to \"pro\".",
    clues: ["Set the tier of the account with email \"dana@example.com\" to \"pro\""],
    sql: "UPDATE customers SET tier = 'pro' WHERE email = 'dana@example.com';",
    collection: "customers",
    sampleDocuments: CUSTOMERS,
    hints: [
      "Only one account changes, so `updateOne` is right.",
      "The filter uses an equality match on `email`.",
      "`{ $set: { tier: \"pro\" } }` assigns the new plan.",
    ],
    referenceAnswer:
      'db.customers.updateOne({ email: "dana@example.com" }, { $set: { tier: "pro" } })',
    rubric: [
      {
        id: "collection",
        label: "Collection",
        weight: 10,
        expectation: { kind: "collection", name: "customers" },
      },
      { id: "method", label: "Method", weight: 20, expectation: { kind: "method", method: "updateOne" } },
      {
        id: "filter",
        label: "Filter condition",
        weight: 30,
        expectation: { kind: "filter", doc: { email: "dana@example.com" } },
      },
      {
        id: "update",
        label: "Update document",
        weight: 40,
        expectation: { kind: "update", doc: { $set: { tier: "pro" } } },
      },
    ],
  },
  {
    id: "easy-big-ticket-orders",
    title: "Big-ticket order watchlist",
    difficulty: "easy",
    operation: "find",
    statement:
      "The finance team flags big-ticket activity and needs every order with a total of at least 200.",
    clues: ["every order with a total of at least 200"],
    sql: "SELECT * FROM orders WHERE total >= 200;",
    collection: "orders",
    sampleDocuments: ORDERS,
    hints: [
      "Filter on the numeric `total` field.",
      "\"At least\" is an inclusive comparison, so `$gte`.",
      "`{ total: { $gte: 200 } }`.",
    ],
    referenceAnswer: "db.orders.find({ total: { $gte: 200 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "orders" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { total: { $gte: 200 } } },
      },
    ],
  },
  {
    id: "easy-pending-order-totals",
    title: "Pending order triage sheet",
    difficulty: "easy",
    operation: "find",
    statement:
      "The shipping desk needs a triage sheet of every order that is still pending, showing only the customerId and the total.",
    clues: ["every order that is still pending", "showing only the customerId and the total"],
    sql: "SELECT customerId, total FROM orders WHERE status = 'pending';",
    collection: "orders",
    sampleDocuments: ORDERS,
    hints: [
      "\"Still pending\" is an equality match on `status`.",
      "The requested output fields go in the second argument.",
      '`{ status: "pending" }` then `{ customerId: 1, total: 1 }`.',
    ],
    referenceAnswer: 'db.orders.find({ status: "pending" }, { customerId: 1, total: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "orders" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { status: "pending" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { customerId: 1, total: 1 },
          variants: [{ customerId: 1, total: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-confirm-order-delivered",
    title: "Confirm a hand-off",
    difficulty: "easy",
    operation: "update",
    statement:
      "The courier signed for the order with _id ObjectId(\"66f1a2b3c4d5e6f7a8b9c0da\"). Record the hand-off by setting its status to \"delivered\".",
    clues: [
      "the order with _id ObjectId(\"66f1a2b3c4d5e6f7a8b9c0da\")",
      "setting its status to \"delivered\"",
    ],
    sql: "UPDATE orders SET status = 'delivered' WHERE _id = '66f1a2b3c4d5e6f7a8b9c0da';",
    collection: "orders",
    sampleDocuments: ORDERS,
    hints: [
      "A single order changes, so use `updateOne`.",
      "Match the order on `_id` and wrap the id in `ObjectId(...)`.",
      'The update is `{ $set: { status: "delivered" } }`.',
    ],
    referenceAnswer:
      'db.orders.updateOne({ _id: ObjectId("66f1a2b3c4d5e6f7a8b9c0da") }, { $set: { status: "delivered" } })',
    rubric: [
      {
        id: "collection",
        label: "Collection",
        weight: 10,
        expectation: { kind: "collection", name: "orders" },
      },
      { id: "method", label: "Method", weight: 20, expectation: { kind: "method", method: "updateOne" } },
      {
        id: "filter",
        label: "Filter condition",
        weight: 30,
        expectation: { kind: "filter", doc: { _id: objectId("66f1a2b3c4d5e6f7a8b9c0da") } },
      },
      {
        id: "update",
        label: "Update document",
        weight: 40,
        expectation: { kind: "update", doc: { $set: { status: "delivered" } } },
      },
    ],
  },
  {
    id: "easy-engineering-roster",
    title: "Engineering roster",
    difficulty: "easy",
    operation: "find",
    statement:
      "The engineering manager needs the roster of everyone in the engineering department, showing only their name and title.",
    clues: ["everyone in the engineering department", "showing only their name and title"],
    sql: "SELECT name, title FROM employees WHERE department = 'engineering';",
    collection: "employees",
    sampleDocuments: EMPLOYEES,
    hints: [
      "Match `department` with an equality filter.",
      "Then trim the output down to the two requested fields.",
      '`{ department: "engineering" }` then `{ name: 1, title: 1 }`.',
    ],
    referenceAnswer: 'db.employees.find({ department: "engineering" }, { name: 1, title: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "employees" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { department: "engineering" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { name: 1, title: 1 },
          variants: [{ name: 1, title: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-high-salary-staff",
    title: "Top earners review",
    difficulty: "easy",
    operation: "find",
    statement:
      "Compensation wants a list of every employee earning 130000 or more a year.",
    clues: ["every employee earning 130000 or more a year"],
    sql: "SELECT * FROM employees WHERE salary >= 130000;",
    collection: "employees",
    sampleDocuments: EMPLOYEES,
    hints: [
      "The base pay lives in the `salary` field.",
      "\"Or more\" means greater than or equal to, so `$gte`.",
      "`{ salary: { $gte: 130000 } }`.",
    ],
    referenceAnswer: "db.employees.find({ salary: { $gte: 130000 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "employees" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { salary: { $gte: 130000 } } },
      },
    ],
  },
  {
    id: "easy-critical-reviews",
    title: "Read the critical reviews",
    difficulty: "easy",
    operation: "find",
    statement:
      "The product team wants to read every review that scored 2 or less, showing only the productId and the rating.",
    clues: ["every review that scored 2 or less", "showing only the productId and the rating"],
    sql: "SELECT productId, rating FROM reviews WHERE rating <= 2;",
    collection: "reviews",
    sampleDocuments: REVIEWS,
    hints: [
      "\"Scored 2 or less\" is an inclusive upper bound.",
      "The operator is `$lte`, and the field is `rating`.",
      '`{ rating: { $lte: 2 } }` then `{ productId: 1, rating: 1 }`.',
    ],
    referenceAnswer: "db.reviews.find({ rating: { $lte: 2 } }, { productId: 1, rating: 1 })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "reviews" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { rating: { $lte: 2 } } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { productId: 1, rating: 1 },
          variants: [{ productId: 1, rating: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-unverified-reviews",
    title: "Unverified review audit",
    difficulty: "easy",
    operation: "find",
    statement:
      "The trust and safety team wants to re-check every review that was not verified before it appears on the site.",
    clues: ["every review that was not verified"],
    sql: "SELECT * FROM reviews WHERE verified = false;",
    collection: "reviews",
    sampleDocuments: REVIEWS,
    hints: [
      "`verified` is a boolean field, so no comparison operator is needed.",
      "Matching `false` is a plain equality filter.",
      '`{ verified: false }`.',
    ],
    referenceAnswer: "db.reviews.find({ verified: false })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "reviews" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { verified: false } },
      },
    ],
  },
  {
    id: "easy-urgent-ticket-queue",
    title: "Urgent ticket queue",
    difficulty: "easy",
    operation: "find",
    statement:
      "Support management wants a queue of every ticket marked urgent, showing only the subject and the status.",
    clues: ["every ticket marked urgent", "showing only the subject and the status"],
    sql: "SELECT subject, status FROM tickets WHERE priority = 'urgent';",
    collection: "tickets",
    sampleDocuments: TICKETS,
    hints: [
      "Urgency is recorded in the `priority` field.",
      "An equality match is enough here.",
      '`{ priority: "urgent" }` then `{ subject: 1, status: 1 }`.',
    ],
    referenceAnswer: 'db.tickets.find({ priority: "urgent" }, { subject: 1, status: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "tickets" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { priority: "urgent" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { subject: 1, status: 1 },
          variants: [{ subject: 1, status: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-ticket-by-id",
    title: "Open one helpdesk ticket",
    difficulty: "easy",
    operation: "find",
    statement: "An agent pulls up the single helpdesk ticket with _id 2 to read the conversation.",
    clues: ["the single helpdesk ticket with _id 2"],
    sql: "SELECT * FROM tickets WHERE _id = 2;",
    collection: "tickets",
    sampleDocuments: TICKETS,
    hints: [
      "Ticket ids are plain numbers, so no `ObjectId(...)` wrapper is needed.",
      "Expecting one document makes `findOne` the natural method.",
      "`db.tickets.findOne({ _id: 2 })`; `find` is accepted too.",
    ],
    referenceAnswer: "db.tickets.findOne({ _id: 2 })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "tickets" } },
      {
        id: "method",
        label: "Method",
        expectation: { kind: "method", method: "findOne", equivalents: ["find"] },
      },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { _id: 2 } },
      },
    ],
  },
  {
    id: "easy-long-sessions",
    title: "Long session report",
    difficulty: "easy",
    operation: "find",
    statement:
      "Product analytics wants every user session lasting at least 30 minutes, showing only the userId and the duration.",
    clues: [
      "every user session lasting at least 30 minutes",
      "showing only the userId and the duration",
    ],
    sql: "SELECT userId, durationMins FROM sessions WHERE durationMins >= 30;",
    collection: "sessions",
    sampleDocuments: SESSIONS,
    hints: [
      "Session length is stored in `durationMins`.",
      "\"At least\" means the inclusive comparison `$gte`.",
      '`{ durationMins: { $gte: 30 } }` then `{ userId: 1, durationMins: 1 }`.',
    ],
    referenceAnswer:
      "db.sessions.find({ durationMins: { $gte: 30 } }, { userId: 1, durationMins: 1 })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "sessions" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { durationMins: { $gte: 30 } } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { userId: 1, durationMins: 1 },
          variants: [{ userId: 1, durationMins: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-incomplete-sessions",
    title: "Dropped-out sessions",
    difficulty: "easy",
    operation: "find",
    statement:
      "Growth wants to win back users who dropped out mid-flow, so it needs every session that was not completed.",
    clues: ["every session that was not completed"],
    sql: "SELECT * FROM sessions WHERE completed = false;",
    collection: "sessions",
    sampleDocuments: SESSIONS,
    hints: [
      "Completion is tracked by the boolean `completed` field.",
      "Matching a boolean needs no operator at all.",
      "`{ completed: false }`.",
    ],
    referenceAnswer: "db.sessions.find({ completed: false })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "sessions" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { completed: false } },
      },
    ],
  },
  {
    id: "easy-overdue-invoices",
    title: "Overdue invoice chase list",
    difficulty: "easy",
    operation: "find",
    statement:
      "Credit control chases late payers and needs every invoice marked overdue, showing only the amount and the currency.",
    clues: ["every invoice marked overdue", "showing only the amount and the currency"],
    sql: "SELECT amount, currency FROM invoices WHERE status = 'overdue';",
    collection: "invoices",
    sampleDocuments: INVOICES,
    hints: [
      "Payment state lives in the `status` field.",
      "An equality match on that field is all you need.",
      '`{ status: "overdue" }` then `{ amount: 1, currency: 1 }`.',
    ],
    referenceAnswer: 'db.invoices.find({ status: "overdue" }, { amount: 1, currency: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "invoices" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { status: "overdue" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { amount: 1, currency: 1 },
          variants: [{ amount: 1, currency: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-large-invoices",
    title: "Material invoices for audit",
    difficulty: "easy",
    operation: "find",
    statement:
      "The auditors want every invoice whose amount is more than 1000 before they sign off the quarter.",
    clues: ["every invoice whose amount is more than 1000"],
    sql: "SELECT * FROM invoices WHERE amount > 1000;",
    collection: "invoices",
    sampleDocuments: INVOICES,
    hints: [
      "Compare the numeric `amount` field against a threshold.",
      "\"More than\" is a strict comparison, so `$gt`.",
      "`{ amount: { $gt: 1000 } }`.",
    ],
    referenceAnswer: "db.invoices.find({ amount: { $gt: 1000 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "invoices" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { amount: { $gt: 1000 } } },
      },
    ],
  },
  {
    id: "easy-low-stock-list",
    title: "Replenishment shortlist",
    difficulty: "easy",
    operation: "find",
    statement:
      "Merchandising wants a replenishment list of every product with fewer than 10 units on hand, showing only the sku and the stock.",
    clues: [
      "every product with fewer than 10 units on hand",
      "showing only the sku and the stock",
    ],
    sql: "SELECT sku, stock FROM products WHERE stock < 10;",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "Units on hand are stored in `stock`.",
      "\"Fewer than\" is a strict comparison, so `$lt`.",
      '`{ stock: { $lt: 10 } }` then `{ sku: 1, stock: 1 }`.',
    ],
    referenceAnswer: "db.products.find({ stock: { $lt: 10 } }, { sku: 1, stock: 1 })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { stock: { $lt: 10 } } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { sku: 1, stock: 1 },
          variants: [{ sku: 1, stock: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-product-by-sku",
    title: "Look up one product by sku",
    difficulty: "easy",
    operation: "find",
    statement:
      "The returns desk needs the name and the price of the single product with the sku \"P-103\".",
    clues: ["the single product with the sku \"P-103\"", "the name and the price"],
    sql: "SELECT name, price FROM products WHERE sku = 'P-103';",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "A stock code is just a string field, so match it with an equality filter.",
      "Only two fields are needed, so pass a projection too.",
      '`db.products.findOne({ sku: "P-103" }, { name: 1, price: 1 })`.',
    ],
    referenceAnswer: 'db.products.findOne({ sku: "P-103" }, { name: 1, price: 1 })',
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      {
        id: "method",
        label: "Method",
        expectation: { kind: "method", method: "findOne", equivalents: ["find"] },
      },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { sku: "P-103" } },
      },
      {
        id: "projection",
        label: "Projection",
        expectation: {
          kind: "projection",
          doc: { name: 1, price: 1 },
          variants: [{ name: 1, price: 1, _id: 0 }],
        },
      },
    ],
  },
  {
    id: "easy-premium-shelf",
    title: "In-store premium shelf",
    difficulty: "easy",
    operation: "find",
    statement:
      "The in-store premium shelf lists anything over 30, so return every product that costs more than 30.",
    clues: ["every product that costs more than 30"],
    sql: "SELECT * FROM products WHERE price > 30;",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "Use the `price` field for the comparison.",
      "\"More than\" is strict, so use `$gt` rather than `$gte`.",
      "`{ price: { $gt: 30 } }`.",
    ],
    referenceAnswer: "db.products.find({ price: { $gt: 30 } })",
    rubric: [
      { id: "collection", label: "Collection", expectation: { kind: "collection", name: "products" } },
      { id: "method", label: "Method", expectation: { kind: "method", method: "find" } },
      {
        id: "filter",
        label: "Filter condition",
        expectation: { kind: "filter", doc: { price: { $gt: 30 } } },
      },
    ],
  },
  {
    id: "easy-reprice-notebook",
    title: "Apply a price cut",
    difficulty: "easy",
    operation: "update",
    statement:
      "The pricing team has approved a promotion. Set the price of the product with the sku \"P-102\" to 10.",
    clues: ["Set the price of the product with the sku \"P-102\" to 10"],
    sql: "UPDATE products SET price = 10 WHERE sku = 'P-102';",
    collection: "products",
    sampleDocuments: PRODUCTS,
    hints: [
      "One product changes, so `updateOne` is the right method.",
      "Identify it with an equality filter on `sku`.",
      "`{ $set: { price: 10 } }`.",
    ],
    referenceAnswer: 'db.products.updateOne({ sku: "P-102" }, { $set: { price: 10 } })',
    rubric: [
      {
        id: "collection",
        label: "Collection",
        weight: 10,
        expectation: { kind: "collection", name: "products" },
      },
      { id: "method", label: "Method", weight: 20, expectation: { kind: "method", method: "updateOne" } },
      {
        id: "filter",
        label: "Filter condition",
        weight: 30,
        expectation: { kind: "filter", doc: { sku: "P-102" } },
      },
      {
        id: "update",
        label: "Update document",
        weight: 40,
        expectation: { kind: "update", doc: { $set: { price: 10 } } },
      },
    ],
  },
];
